### ISSUE TITLE
LOGIN BUTTONS

### ISSUE THREAD

**Issue by abdulhajees** [mkandan1/mymamcet#20]
The Buttons for LOGIN
With Google + Microsoft
Showing the error data instead of the button (verified in Mobile.) 
![Screenshot_20240322-123601](https://github.com/mkandan1/mymamcet/assets/84639525/61c7cb1e-ee6d-4016-bba8-e94b2ad77bbc)

**Comment by manirolo** [comment]
Bug fixed via PR (https://github.com/mkandan1/mymamcet/pull/23)
