### ISSUE TITLE
PASSWORD - VISIBILITY

### ISSUE THREAD

**Issue by abdulhajees** [mkandan1/mymamcet#22]
The view password option is not working.

- both android and windows.(Chrome browser)
- working with (micro soft edge - one time only)

**Comment by manirolo** [comment]
Hi @aj05hacker 

I reviewed your all submitted issues and everything is good. I appericiate your efforts in finding and reporting the bugs to this project. Keep help me to find bugs.

**Comment by manirolo** [comment]
Bug fixed via PR (https://github.com/mkandan1/mymamcet/pull/23)
